name: RPM Build

# Controls when the action will run. Triggers the workflow on push
on: push

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: registry.fedoraproject.org/fedora:38

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    - name: Run rpmbuild
      run: |
        dnf install -y rpm-build dnf-plugins-core
        dnf builddep -y ./applet-window-appmenu.spec
        mkdir -p SOURCES
        curl -L -o SOURCES/applet-window-appmenu-0.8.0.tar.gz https://github.com/psifidotos/applet-window-appmenu/archive/refs/tags/v0.8.0.tar.gz
        # tar xf ./applet-window-appmenu.tar.gz -C ./SOURCES
        # mv SOURCES/* SOURCES/applet-window-appmenu
        rpmbuild --define "_topdir $(pwd)" -bb applet-window-appmenu.spec
        ls -la ./RPMS
    
    # - name: Print output
    #   run: echo ${{steps.rpm.outputs.source_rpm_path}}
    
    - name: Upload artifact
      uses: softprops/action-gh-release@v1
      with:
        # Artifact name
        #name: Binary RPM
        # Directory containing files to upload
        #path: ${{ steps.rpm.outputs.rpm_dir_path }}
        files: ./RPMS/*.rpm
